name 'juliengk-docker'
version '0.1.3'
source 'git://github.com/juliengk/puppet-module-docker.git'
author 'juliengk'
license 'Apache License, Version 2.0'
summary 'Manage docker'
description 'Manage docker'
project_page 'https://github.com/juliengk/puppet-module-docker'

dependency 'puppetlabs/stdlib', '>= 4.5.1'
dependency 'juliengk/stdlibplus', '>= 0.1.0'
dependency 'juliengk/env', '>= 0.1.0'
